### PR TITLE
nested describe call for buddy #19

### PR DESCRIPTION
**Pull request by akitsu-sanae**
This commit solves issue #19.
I'm new to this project, so please tell me if something is wrong.

### CODE REVIEW

**Comment by AlexHaxe** [comment]
thanks for working on that issue!

as far as I can see it seems to work - I've only ran buddy and utest samples and didn't do a thorough test, might have time to do that later

can you add a nested testcase to `samples/buddy`?

**Comment by akitsu-sanae** [comment]
I added a nested test case as `TestCase4`.

**Comment by AlexHaxe** [comment]
I've done some more testing and found two issues:
1. I would expect only one TestCase4 with testOuter as a child of the first one:
testadapter_nested_buddy
2. your change in `TestPositions` messes up reported positions for nested testcases of utest, munit, hexunit and haxeunit (tink_testrunner is fine as far as I can see, but it also misses nesting support, so that's probably why it's unaffected)
it also seems to reorder treeview positions between your version and v1.2.8.

in extension to 1. when you have two classes that use the same top level `describe` current behaviour is to add a new top level node with same name. with your changes a nested `describe` gets merged with the first one, while direct `it` childs of it get a second top level treeview entry.
in screenshow below you can see `TestCase5` as a child of `describe("TestCase")` inside `TestCase3.hx` which lands in top level `describe("TestCase")` of `Main.hx`, while `testSuccess3` is further down in its own `TestCase` tree item
20200730_testadapter_nested_buddy_2

I'm undecided if we should merge two different test suites that share the same description (or description paths), but it should be consistent and not confusing.
I don't use buddy, so I'm not sure how often you will have test suites sharing the same name (maybe if developers are lazy and just copy test classes and forget to rename them).
I also don't know what the consensus of buddy and other bdd testing framework communities concerning duplicate descriptions is, so maybe you or @Hersir88 have some more insight on how to deal with that.

**Comment by hansagames** [comment]
@AlexHaxe same name for test case can happen but not very often, like sam file name but different context like utils files, but would say its test written responsibility to make them unique if necessary, I don't have strong oppinion if same names would need to be merged or not, but would vote for not merging them to see difference between test cases

**Comment by AlexHaxe** [comment]
you are right if we merge them then people will not realize that they used the same description names in different files. and it might be harder to figure out which tests they need to fix. if it's two separate tree items with identical names, then everything from one file is grouped together and it's easier to correct.

so existing behaviour is desirable, we just need to figure out how to add hierarchy info to buddy without breaking others.
I guess we can always do a `#if buddy` conditional to limit changes to buddy tests

**Comment by AlexHaxe** [comment]
your latest change looks better, thanks for continuing your work!

When I run buddy sample I see a merge happening between `Main.TestCase` and `tests.Test3.TestCase`:

20200817_testadapter_nested_buddy

while technically correct, I think the consensus was to not merge, if two `describe` calls happen to have identical description paths. 
I'm not sure how to best address it, maybe adding classnames would be an option, but even then you could end up having the same classname in two different packages using identical `describe` calls, or two identical `describe`s in the same class. 

Also I found that your change in `TestPositions.hx` doesn't make any difference whether it's in or out - though I might be testing wrong or I looked at the wrong places.

**Comment by akitsu-sanae** [comment]
I believe my last commit makes `describe`s which have same description but different position not be merged in VSCode Test Panel.
In the left panel, the upper `TestCase` is the `describe` in `Main.hx`, and the lower is one in `tests/TestCase3.hx`
ss

I guess that my previous change in `TestPositions.hx` make sense, and this is necessary for nesting describes in buddy.  
Now in buddy testing, `className` may have parent describe's info, but what is needed here is `className` without such info.  
I think that the change will make difference when testing nested `describe` in buddy.

**Comment by AlexHaxe** [comment]
your latest commit correctly distinguishes describe paths and puts them into different tree hierarchies.
however your change introduces two new side effects:

1. for at least utest and munit it adds a new top level tree item for every class regardless of whether they share the same package structure. 
package `tests` should only appear once, having `TestCase` and `TestCase3` child nodes:
20200819_testadapter_nested_utest
left side shows results with your changes vs. right side from version 1.2.9 (both utest)

2. applying file and line information to all `TestSuiteInfo` instances adds a `Show Source` button to all tree items. which is not bad in itself, however for buddy clicking on one of the top level tree items it jumps to package definition of its containing file. it also happens when you click `Show Source` on `TestCase4Inner` which is even more unexpected. 
it kind of works for other test frameworks (like utest), where it will jump to the line containing `class <TestSuite>`. however I think that is just a happy coincidence and a result of side effect number 1 which creates a separate tree hierarchy for each class. 
once that gets fixed, it will probably jump to one arbitrary file in that package (probably first or last one added).
clicking `Show Source` on a package doesn't really make sense for class based test frameworks with nested package structure (usually package structure of tests mirrors that of the sources being tested), because one has to expect more than one file in a package and there will be no correct file to go to since all of them belong to that package.

**Comment by akitsu-sanae** [comment]
This time, I think that my latest commit solves both side effect problems.
In my environment, utest and buddy samples seem to be working well.

**Comment by AlexHaxe** [comment]
Sorry for the late reply, I was a bit overwhelmed with work.

I just tested your latest changes and I still see two top level `tests` tree entries for the two testclasses in `tests` package for utest, munit and haxeunit (probably all non buddy samples). so I cannot confirm first side effect from my last post as fixed.

I feel like we are adding a lot of changes to common code that affects all test frameworks. which always carries the risk of introducing unwanted side effects.

maybe we need to explore a different approach. there are still some tricky areas, since I haven't thought everything though, however how about we do:
- subclass or patch `Spec` class to hold a `PosInfos` object
- get `SuiteRunner` to use and fill pos into custom `Spec` class <= tricky part
- build hierarchy of testsuite names in `Reporter` <= detecting duplicate testsuites might also be tricky
- use position from custom `Spec` class to report test position (might require a new SuiteIdentifier)

that way we might be able to report everything correctly with changes restricted to buddy integration. again I'm not sure if it's doable, but I think it's worth thinking about it

**Comment by akitsu-sanae** [comment]
I was thinking how to implement your approach, but I found it is not doable.

The part of making tree structure is in `HaxeTestAdapter.hx`, and there, suite's id is represented in `string` type.
And, suite's node in the test tree structure is build with id in 'string' type.
Whether suite's node needs `file` as position or not depends on the test-framework (buddy needs, but utest dones not).
So, I think `HaxeTestAdapter.hx` needs some code depending on test-framework in the making tree structure part.
Or, we can move making tree structure part into each test-framework's reporting part to keep `HaxeTestAdapter.hx` free from test-framework's dependences.  This needs more changes.

I believe my latest commit is minimal change to fix this problem.

**Comment by AlexHaxe** [comment]
yeah, my proposed approach would require a macro to dig deep into `SuitesRunner`s code to replace `new Spec(desc, pos.fileName)` with something like `new _testadapter.buddy.TestAdapterSpec(desc, pos)` in order to work. I don't think it's impossible, but there is no easy `PatchTools` solution for it and it might be a fragile solution that breaks whenever buddy changes its implementation. on the other hand most test framework integrations break when they change internals (happened e.g. with recent utest).

your new approach looks promising. however having a conditional inside the VSCode extension part is not desirable, because that would require two "binaries" and we have no way of switching between them or detecting a buddy test environment.

since we control the data structure used by test frameworks to report to test adapter, what if we add an additional flag or field to make `HaxeTestAdapter` use a different compare function when set? that way we can support buddy and all the other frameworks without needing two different "binaries" or even a dedicated buddy extension.

your latest change seems to have lost the ability to click `Show source` for nested tests, because their line numbers are set to `null`.

**Comment by AlexHaxe** [comment]
I got curious about the `Spec` replacement idea and started something on [buddy_spec_replace](https://github.com/vshaxe/haxe-test-adapter/tree/buddy_spec_replace) branch.
it still has one glitch, where a nested `describe` needs to be after at least one `it` call, otherwise it will put parent into tree twice: one with all `it` childs and one with all nested `describe` childs. 
otherwise it seems to be working, unless I'm missing something...

**Comment by akitsu-sanae** [comment]
Thanks, it looks good.
I'm looking forward to seeing it done.

**Comment by AlexHaxe** [comment]
I think I've figured out filtering and sorting of nested test cases in my latest commit.
I will merge `buddy_spec_replace` branch over to master and close this pull request unless someone objects.

thank you for the work you put in. it's not an easy project to contribute to, since there are many different pieces and areas that one needs to keep in balance. and despite being a test-adapter working with many different test frameworks we don't really have good unittests (or any at all). yet you persisted and came up with solutions for the challenges and issues that were pointed out.

**Comment by AlexHaxe** [comment]
closed by #22

**Pull request closed without merging**
